education:
  project:
    per_page: 16
    truncate: 100
  technique:
    per_page: 6
    truncate: 100
  index:
    max_learning_program_desc: 150
    max_learning_program_name: 20
    max_learning_program: 3
  trainings:
    per_page: 5
  page_404_url: "public/404"
  related_project:
    limit: 20
home:
  limit: 8
home_trainings_limit: 8
