languages: {en: "English", vi: "Tiếng Việt", jp: "日本語"}
education:
  home_page:
    introduction_video_bg_image: "/assets/images/services/main-bg.jpg"
    introduction_video_link: "https://www.youtube.com/watch?v=eTx-_mhAb8M"
    introduction_video_link_cover_image: "/assets/images/services/video.jpg"
    introduction_video_link_play_button: "/assets/images/icons/video-play.png"
    course_count: 846
    trainee_count: 21500
    trainer_count: 408
    need_content_img: "/assets/images/services/iphone6.png"
    clients_say_bg: "/assets/images/services/home-testi-bg.jpg"
    client_img_3: "/assets/images/testimonials/3.jpg"
    client_img_2: "/assets/images/testimonials/2.jpg"
    client_img_1: "/assets/images/testimonials/1.jpg"
    team_member_img_1: "/assets/images/team/3.jpg"
    team_member_img_2: "/assets/images/team/2.jpg"
    team_member_img_3: "/assets/images/team/8.jpg"
    team_member_img_4: "/assets/images/team/4.jpg"
    client1_logo: "/assets/images/clients/1.png"
    client2_logo: "/assets/images/clients/2.png"
    client3_logo: "/assets/images/clients/3.png"
    client4_logo: "/assets/images/clients/4.png"
    client5_logo: "/assets/images/clients/5.png"
    client6_logo: "/assets/images/clients/6.png"
    client7_logo: "/assets/images/clients/7.png"
    client8_logo: "/assets/images/clients/8.png"
    client9_logo: "/assets/images/clients/9.png"
    client10_logo: "/assets/images/clients/10.png"
    slide1_img: "/assets/welcome1.jpg"
    slide2_poster: "/assets/videos/explore.jpg"
    slide2_video_webm: "/assets/videos/explore.webm"
    slide2_video_mp4: "/assets/videos/explore.mp4"
    slide3_img: "/assets/welcome2.jpg"
    framgia_email: "staff@framgia.com"
    framgia_phone: "+91-11-6541-6369"
  number_one: 1
  project:
    modal_description: "#modal_description"
    modal_core: "#modal_core"
    modal_release: "#modal_release"
    per_page: 12
    truncate: 100
    link_truncate: 28
    content_truncate: 120
  technique:
    per_page: 6
    truncate: 100
    max_name_length: 100
  index:
    max_learning_program_desc: 150
    max_learning_program_name: 20
    max_learning_program: 3
  trainings:
    per_page: 5
    limit_string: 200
  page_404_url: "public/404"
  related_project:
    limit: 20
  related_post:
    limit: 4
  projects:
    textarea_rows: 8
    split_array: 4
    min_array_size: 3
  mess_success: "success"
  mess_notice: "notice"
  feedback_form_rows: 6
  feedback_form_cols: 30
  feedback:
    max_name_length: 50
    max_email_length: 255
    max_phone_number_length: 255
    max_subject_length: 255
    min_subject_length: 3
    min_content_length: 10
    max_content_length: 255
  category:
    max_length_title: 200
  posts:
    max_length_title: 200
    content_character_display: 255
    per_page: 20
  comment:
    per_page: 3
    max_content_length: 255
  post:
    comment_form_cols: 58
    comment_form_rows: 4
    comment_user_avatar_height: 60
    comment_user_avatar_width: 60
    popular_posts_limit: 3
    newest_post_limit: 3
    title_max_length: 255
    title_min_length: 10
    content_min_length: 10
    comment_item_avatar_size: "60x60"
home:
  limit: 8
home_trainings_limit: 8
company:
  country: ["United States", "Japan", "Germany", "Korea"]
  max_length_name: 50
default_user_password: {"password": "123456"}
courses:
  modal_detail: "#modal_detail"
  home_limit: 4
  index_limit: 8
  max_course_detail: 80
  truncate_other_course: 200
  truncate_detail_course: 200
  other_coures_limit: 12
user:
  max_length_name: 50
max_length_title: 50
hiring_type:
  max_length_name: 50
jobs:
  per_page: 5
  image_size: 100%
  image_url: "/assets/welcome1.jpg"
  image_company_size: 32x32
  limit_user_show: 3
  image_member_size: 70x70
  image_member_url: "/assets/avatar.jpg"
industries:
  max_length_name: 50
activity:
  per_page: 10
