languages: {en: "English", vi: "Tiếng Việt", jp: "日本語"}
education:
  number_one: 1
  project:
    modal_description: "#modal_description"
    modal_core: "#modal_core"
    modal_release: "#modal_release"
    per_page: 12
    truncate: 100
    link_truncate: 28
    content_truncate: 80
  technique:
    per_page: 6
    truncate: 100
    max_name_length: 100
  index:
    max_learning_program_desc: 150
    max_learning_program_name: 20
    max_learning_program: 3
  trainings:
    per_page: 5
    limit_string: 200
  page_404_url: "public/404"
  related_project:
    limit: 20
  related_post:
    limit: 4
  projects:
    textarea_rows: 8
    split_array: 4
    min_array_size: 3
  mess_success: "success"
  mess_notice: "notice"
  feedback_form_rows: 6
  feedback_form_cols: 30
  feedback:
    max_name_length: 50
    max_email_length: 255
    max_phone_number_length: 255
    max_subject_length: 255
    min_subject_length: 3
    min_content_length: 10
    max_content_length: 255
  category:
    max_length_title: 200
  posts:
    max_length_title: 200
    content_character_display: 255
    per_page: 20
  comment:
    per_page: 3
    max_content_length: 255
  post:
    comment_form_cols: 58
    comment_form_rows: 4
    comment_user_avatar_height: 60
    comment_user_avatar_width: 60
    popular_posts_limit: 3
    newest_post_limit: 3
    title_max_length: 255
    title_min_length: 10
    content_min_length: 10
    comment_item_avatar_size: "60x60"
home:
  limit: 8
home_trainings_limit: 8
company:
  country: ["United States", "Japan", "Germany", "Korea"]
  max_length_name: 50
default_user_password: {"password": "123456"}
courses:
  home_limit: 4
  index_limit: 8
  max_course_detail: 30
  truncate_other_course: 200
  truncate_detail_course: 500
  other_coures_limit: 3
user:
  max_length_name: 50
max_length_title: 50
hiring_type:
  max_length_name: 50
jobs:
  per_page: 5
  image_size: 100%
  image_url: "/assets/welcome1.jpg"
  image_company_size: 32x32
  limit_user_show: 3
  image_member_size: 70x70
  image_member_url: "/assets/avatar.jpg"
industries:
  max_length_name: 50
